/*
NAVICAT MYSQL DATA TRANSFER

SOURCE SERVER         : LOCALHOST
SOURCE SERVER VERSION : 80013
SOURCE HOST           : LOCALHOST:3306
SOURCE DATABASE       : HRM

TARGET SERVER TYPE    : MYSQL
TARGET SERVER VERSION : 80013
FILE ENCODING         : 65001

DATE: 2019-08-30 18:12:43
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR HRM_ROLE_AUTH
-- ----------------------------
DROP TABLE IF EXISTS `HRM_ROLE_AUTH`;
CREATE TABLE `HRM_ROLE_AUTH` (
  `ROLE_ID` VARCHAR(45) NOT NULL,
  `AUTH_TYPE` VARCHAR(45) NOT NULL COMMENT 'C,U,R,D',
  `ITEM` VARCHAR(45) NOT NULL,
  `ITEM_TYPE` VARCHAR(45) NOT NULL COMMENT '1:MENU,2:BUTTON',
  PRIMARY KEY (`ROLE_ID`,`ITEM`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

-- ----------------------------
-- RECORDS OF HRM_ROLE_AUTH
-- ----------------------------

-- ----------------------------
-- TABLE STRUCTURE FOR HRM_ROLE_INFO
-- ----------------------------
DROP TABLE IF EXISTS `HRM_ROLE_INFO`;
CREATE TABLE `HRM_ROLE_INFO` (
  `ROLE_ID` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '角色ID',
  `ROLE_NAME` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI DEFAULT NULL,
  `PARENT_ROLE` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI DEFAULT NULL COMMENT '上级角色ID',
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 COMMENT='角色信息表';

-- ----------------------------
-- RECORDS OF HRM_ROLE_INFO
-- ----------------------------
INSERT INTO `HRM_ROLE_INFO` VALUES ('ADMIN', 'ADMIN', NULL);
INSERT INTO `HRM_ROLE_INFO` VALUES ('R_CN', '出纳', NULL);
INSERT INTO `HRM_ROLE_INFO` VALUES ('R_CWZG', '财务主管', NULL);
INSERT INTO `HRM_ROLE_INFO` VALUES ('R_KHJL', '客户经理', NULL);
INSERT INTO `HRM_ROLE_INFO` VALUES ('R_SCZG', '市场主管', NULL);
INSERT INTO `HRM_ROLE_INFO` VALUES ('R_SQ', '售前', NULL);

-- ----------------------------
-- TABLE STRUCTURE FOR HRM_USER_BASIC_INFO
-- ----------------------------
DROP TABLE IF EXISTS `HRM_USER_BASIC_INFO`;
CREATE TABLE `HRM_USER_BASIC_INFO` (
  `USER_ID` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '用户ID内码',
  `USER_NAME` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '用户姓名',
  `USER_ACCNT` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI DEFAULT NULL COMMENT '用户登录账号',
  `SALT` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI DEFAULT NULL COMMENT '盐',
  `PASSWORD` VARCHAR(100) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI DEFAULT NULL COMMENT '用户登录密码',
  `IS_VALID` VARCHAR(1) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI DEFAULT NULL,
  `UPDATE_DATE` DATETIME DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

-- ----------------------------
-- RECORDS OF HRM_USER_BASIC_INFO
-- ----------------------------
INSERT INTO `HRM_USER_BASIC_INFO` VALUES ('1', 'ADMIN', 'ADMIN', NULL, '123', '1', '2019-08-08 00:00:00');
INSERT INTO `HRM_USER_BASIC_INFO` VALUES ('2', '我是售前', 'SQ_1', NULL, '123', '1', '2019-08-28 16:50:24');
INSERT INTO `HRM_USER_BASIC_INFO` VALUES ('3', '我是出纳', 'CN_1', NULL, '123', '1', '2019-08-28 16:51:07');
INSERT INTO `HRM_USER_BASIC_INFO` VALUES ('4', '我是财务主管1', 'CWZG1', NULL, '123', '1', '2019-08-28 16:51:32');
INSERT INTO `HRM_USER_BASIC_INFO` VALUES ('5', '我是客户经理', 'KHJL_1', NULL, '123', '1', '2019-08-28 16:51:52');
INSERT INTO `HRM_USER_BASIC_INFO` VALUES ('6', '我是市场主管1', 'SCZG1', NULL, '123', '1', '2019-08-28 16:52:09');
INSERT INTO `HRM_USER_BASIC_INFO` VALUES ('7', '我是市场主管2', 'SCZG2', '', '123', '1', '2019-08-28 16:52:09');
INSERT INTO `HRM_USER_BASIC_INFO` VALUES ('8', '我是财务主管2', 'CWZG2', '', '123', '1', '2019-08-28 16:51:32');

-- ----------------------------
-- TABLE STRUCTURE FOR HRM_USER_ROLE_REL
-- ----------------------------
DROP TABLE IF EXISTS `HRM_USER_ROLE_REL`;
CREATE TABLE `HRM_USER_ROLE_REL` (
  `USER_ID` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL,
  `ROLE_ID` VARCHAR(45) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL,
  `UPDATE_DATE` DATETIME DEFAULT NULL,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 COMMENT='用户角色关联表';

-- ----------------------------
-- RECORDS OF HRM_USER_ROLE_REL
-- ----------------------------
INSERT INTO `HRM_USER_ROLE_REL` VALUES ('1', 'ADMIN', '2019-08-08 23:49:24');
INSERT INTO `HRM_USER_ROLE_REL` VALUES ('2', 'R_SQ', '2019-08-08 23:49:24');
INSERT INTO `HRM_USER_ROLE_REL` VALUES ('3', 'R_CN', '2019-08-28 16:53:49');
INSERT INTO `HRM_USER_ROLE_REL` VALUES ('4', 'R_CWZG', '2019-08-28 16:54:05');
INSERT INTO `HRM_USER_ROLE_REL` VALUES ('5', 'R_KHJL', '2019-08-28 16:54:17');
INSERT INTO `HRM_USER_ROLE_REL` VALUES ('6', 'R_SCZG', '2019-08-28 16:54:40');
INSERT INTO `HRM_USER_ROLE_REL` VALUES ('7', 'R_SCZG', '2019-08-30 11:15:46');
INSERT INTO `HRM_USER_ROLE_REL` VALUES ('8', 'R_CWZG', '2019-08-30 11:16:01');
