server:
  port: 8083

mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:mapper/*/*Mapper.xml
# 数据源
custom.jdbc:
            crm:
              driverClassName: com.mysql.cj.jdbc.Driver
              username: root
              password: 1233Trip_mysql
              url: jdbc:mysql://127.0.0.1:3306/crm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
              max-idle: 5
              max-wait: 10000
              min-idle: 1
              initial-size: 5
            workflow:
              driverClassName: com.mysql.cj.jdbc.Driver
              username: root
              password: 1233Trip_mysql
              url: jdbc:mysql://127.0.0.1:3306/work_flow?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
              max-idle: 5
              max-wait: 10000
              min-idle: 1
              initial-size: 5
            names: crm,workflow
spring.application:
    name: tavern-crm