server:
  port: 8080

zuul:
  routes:
    tavern-auth-center:
      path: /login/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    tavern-crm:
      path: /crm/**
      url: http://127.0.0.1:8083/

tavern.security.jwt.secret: tavern
