server:
  port: 8080

spring:
  application:
    name: tavern-gateway

zuul:
  routes:
    tavern-auth-center:
      path: /auth/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders: Cookie,Set-Cookie
    tavern-crm:
      path: /crm/**
      url: http://127.0.0.1:8083/
    tavern-hrm:
      path: /hrm/**
      url: http://127.0.0.1:8084/
    tavern-alleria:
      path: /alleria/**
      url: http://127.0.0.1:8082/
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

tavern.security.jwt.secret: tavern
