import axios from '../axios'

/*
 * 菜单管理模块
 */

 // 保存
export const save = (data) => {
    return axios({
        url: '/menu/save',
        method: 'post',
        data
    })
}
// 删除
export const batchDelete = (data) => {
    return axios({
        url: '/menu/delete',
        method: 'post',
        data
    })
}
// 查找导航菜单树
export const findNavTree = (params) => {
     /*axios({
        url: '/menu/findNavTree',
        method: 'get',
        params
    })*/
  const navTreeData = {
    "code": 200,
    "msg": null,
    "data": [{
      "id": 1,
      "createBy": null,
      "createTime": null,
      "lastUpdateBy": null,
      "lastUpdateTime": null,
      "parentId": 0,
      "name": "系统管理",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "el-icon-setting",
      "orderNum": 0,
      "delFlag": 0,
      "parentName": null,
      "level": 0,
      "children": [{
        "id": 2,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "用户管理",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": [{
          "id": 21,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 2,
          "name": "客户管理",
          "url": "/sys/client",
          "perms": null,
          "type": 1,
          "icon": "el-icon-user-solid",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "用户管理",
          "level": 2,
          "children": []
        },{
          "id": 22,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 2,
          "name": "会计管理",
          "url": "/sys/accountant",
          "perms": null,
          "type": 1,
          "icon": "el-icon-user",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "用户管理",
          "level": 2,
          "children": []
        }]
      }, {
        "id": 4,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "角色管理",
        "url": "/sys/role",
        "perms": null,
        "type": 1,
        "icon": "el-icon-view",
        "orderNum": 4,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      }, {
        "id": 5,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "菜单管理",
        "url": "/sys/menu",
        "perms": null,
        "type": 1,
        "icon": "el-icon-menu",
        "orderNum": 5,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      }, ]
    }, {
      "id": 43,
      "createBy": "admin",
      "createTime": "2018-12-27T02:57:29.000+0000",
      "lastUpdateBy": "admin",
      "lastUpdateTime": "2018-12-27T03:02:26.000+0000",
      "parentId": 0,
      "name": "票据管理",
      "url": "",
      "perms": "",
      "type": 0,
      "icon": "el-icon-message",
      "orderNum": 1,
      "delFlag": 0,
      "parentName": null,
      "level": 0,
      "children": [{
        "id": 431,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": "admin",
        "lastUpdateTime": "2018-12-27T03:03:45.000+0000",
        "parentId": 6,
        "name": "银行流水",
        "perms": null,
        "type": 1,
        "icon": "el-icon-bank-card",
        "orderNum": 0,
        "delFlag": 0,
        "parentName": "票据管理",
        "level": 1,
        "children": [{
          "id": 4311,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": "admin",
          "lastUpdateTime": "2018-12-27T03:03:45.000+0000",
          "parentId": 431,
          "name": "流水上传",
          "url": "/bank/upload",
          "perms": null,
          "type": 1,
          "icon": "el-icon-upload",
          "orderNum": 0,
          "delFlag": 0,
          "parentName": "银行流水",
          "level": 2,
          "children": []
        },{
          "id": 4312,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": "admin",
          "lastUpdateTime": "2018-12-27T03:03:45.000+0000",
          "parentId": 431,
          "name": "流水查询",
          "url": "/bank/query",
          "perms": null,
          "type": 2,
          "icon": "el-icon-search",
          "orderNum": 0,
          "delFlag": 0,
          "parentName": "银行流水",
          "level": 1,
          "children": []
        }]
      }, {
        "id": 38,
        "createBy": "admin",
        "createTime": "2018-11-02T12:02:15.000+0000",
        "lastUpdateBy": "admin",
        "lastUpdateTime": "2018-12-27T03:03:53.000+0000",
        "parentId": 43,
        "name": "发票清单",
        "perms": "",
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "票据管理",
        "level": 1,
        "children": [{
          "id": 381,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": "admin",
          "lastUpdateTime": "2018-12-27T03:03:45.000+0000",
          "parentId": 43,
          "name": "发票上传",
          "url": "/invoice/upload",
          "perms": null,
          "type": 1,
          "icon": "el-icon-upload",
          "orderNum": 0,
          "delFlag": 0,
          "parentName": "发票清单",
          "level": 2,
          "children": []
        },{
          "id": 382,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": "admin",
          "lastUpdateTime": "2018-12-27T03:03:45.000+0000",
          "parentId": 43,
          "name": "发票查询",
          "url": "/invoice/query",
          "perms": null,
          "type": 2,
          "icon": "el-icon-search",
          "orderNum": 0,
          "delFlag": 0,
          "parentName": "发票清单",
          "level": 1,
          "children": []
        }]
      },{
        "id": 35,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": "admin",
        "lastUpdateTime": "2018-12-27T03:04:18.000+0000",
        "parentId": 0,
        "name": "增值税",
        "url": "/zzs/upload",
        "perms": null,
        "type": 1,
        "icon": "el-icon-money",
        "orderNum": 3,
        "delFlag": 0,
        "parentName": null,
        "level": 0,
        "children": []
      },{
        "id": 36,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": "admin",
        "lastUpdateTime": "2018-12-27T03:04:18.000+0000",
        "parentId": 0,
        "name": "专票补票(其它票据)",
        "url": "/extraInvoice/query",
        "perms": null,
        "type": 1,
        "icon": "el-icon-document-copy",
        "orderNum": 3,
        "delFlag": 0,
        "parentName": null,
        "level": 0,
        "children": []
      },{
        "id": 37,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": "admin",
        "lastUpdateTime": "2018-12-27T03:04:18.000+0000",
        "parentId": 0,
        "name": "工资单",
        "perms": null,
        "type": 1,
        "icon": "el-icon-document-copy",
        "orderNum": 3,
        "delFlag": 0,
        "parentName": null,
        "level": 0,
        "children": [{
          "id": 371,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": "admin",
          "lastUpdateTime": "2018-12-27T03:03:45.000+0000",
          "parentId": 43,
          "name": "工资上传",
          "url": "/salary/upload",
          "perms": null,
          "type": 1,
          "icon": "el-icon-upload",
          "orderNum": 0,
          "delFlag": 0,
          "parentName": "发票清单",
          "level": 2,
          "children": []
        },{
          "id": 372,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": "admin",
          "lastUpdateTime": "2018-12-27T03:03:45.000+0000",
          "parentId": 43,
          "name": "工资查询",
          "url": "/salary/query",
          "perms": null,
          "type": 2,
          "icon": "el-icon-search",
          "orderNum": 0,
          "delFlag": 0,
          "parentName": "发票清单",
          "level": 1,
          "children": []
        }]
      }]
    },
      {
        "id": 8,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 0,
        "name": "客户登记",
        "url": null,
        "perms": null,
        "type": 0,
        "icon": "el-icon-s-custom",
        "orderNum": 0,
        "delFlag": 0,
        "parentName": null,
        "level": 0,
        "children":  [{
            "id": 81,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "parentId": 8,
            "name": "客户信息",
            "url": "/preSales/customer",
            "perms": null,
            "type": 1,
            "icon": "el-icon-user-solid",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "客户登记",
            "level": 2,
            "children": []
          },{
            "id": 82,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "parentId": 8,
            "name": "订单管理",
            "url": "/sys/user",
            "perms": null,
            "type": 1,
            "icon": "el-icon-s-order",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "客户登记",
            "level": 2,
            "children": []
        }]
      },]
  }
  return navTreeData
}
// 查找导航菜单树
export const findMenuTree = () => {
    return axios({
        url: '/menu/findMenuTree',
        method: 'get'
    })
}
